In [44]:
try:
    import tensorflow as tf
    from tensorflow.python import keras
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    %matplotlib inline
    from sklearn.ensemble import VotingClassifier
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.svm import SVC
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import confusion_matrix,classification_report
    from keras.models import Sequential
    from keras.layers import Dense
    from sklearn.preprocessing import LabelEncoder
    print('Library Loaded .........')
except:
    print('One or More Library was not Found ! ')

Library Loaded .........

In [45]:
df = pd.read_csv("career_pred.csv")

In [46]:
df.head()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,69,63,78,87,94,94,87,84,61,9,...,Prayer books,salary,no,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,78,62,73,60,71,70,73,84,91,12,...,Childrens,salary,yes,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,71,86,91,87,61,81,72,72,94,11,...,Travel,Work,no,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,76,87,60,84,89,73,62,88,69,7,...,Romance,Work,yes,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,92,62,90,67,71,89,73,71,73,4,...,Cookbooks,salary,no,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst

In [47]:
df.shape

(20000, 39)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Acedamic percentage in Operating Systems  20000 non-null  int64
 1   percentage in Algorithms                  20000 non-null  int64
 2   Percentage in Programming Concepts        20000 non-null  int64
 3   Percentage in Software Engineering        20000 non-null  int64
 4   Percentage in Computer Networks           20000 non-null  int64
 5   Percentage in Electronics Subjects        20000 non-null  int64
 6   Percentage in Computer Architecture       20000 non-null  int64
 7   Percentage in Mathematics                 20000 non-null  int64
 8   Percentage in Communication skills        20000 non-null  int64
 9   Hours working per day                     20000 non-null  int64
 10  Logical quotient rating                   20000 non-null  int64
 11  hackathons                                20000 non-null  int64
 12  coding skills rating                      20000 non-null  int64
 13  public speaking points                    20000 non-null  int64
 14  can work long time before system?         20000 non-null  object
 15  self-learning capability?                 20000 non-null  object
 16  Extra-courses did                         20000 non-null  object
 17  certifications                            20000 non-null  object
 18  workshops                                 20000 non-null  object
 19  talenttests taken?                        20000 non-null  object
 20  olympiads                                 20000 non-null  object
 21  reading and writing skills                20000 non-null  object
 22  memory capability score                   20000 non-null  object
 23  Interested subjects                       20000 non-null  object
 24  interested career area                    20000 non-null  object
 25  Job/Higher Studies?                       20000 non-null  object
 26  Type of company want to settle in?        20000 non-null  object
 27  Taken inputs from seniors or elders       20000 non-null  object
 28  interested in games                       20000 non-null  object
 29  Interested Type of Books                  20000 non-null  object
 30  Salary Range Expected                     20000 non-null  object
 31  In a Realtionship?                        20000 non-null  object
 32  Gentle or Tuff behaviour?                 20000 non-null  object
 33  Management or Technical                   20000 non-null  object
 34  Salary/work                               20000 non-null  object
 35  hard/smart worker                         20000 non-null  object
 36  worked in teams ever?                     20000 non-null  object
 37  Introvert                                 20000 non-null  object
 38  Suggested Job Role                        20000 non-null  object
dtypes: int64(14), object(25)
memory usage: 6.0+ MB

## Checking for Null Values

To ensure data quality, it is important to check for any null values in the dataset. The following code calculates the number of null values in each column of the dataframe `df`:

```python
    null_values = df.isnull().sum()
    print(null_values)
```

This will help us identify if there are any missing values that need to be addressed before proceeding with further analysis.

In [49]:
null_values = df.isnull().sum()
print(null_values)

Acedamic percentage in Operating Systems    0
percentage in Algorithms                    0
Percentage in Programming Concepts          0
Percentage in Software Engineering          0
Percentage in Computer Networks             0
Percentage in Electronics Subjects          0
Percentage in Computer Architecture         0
Percentage in Mathematics                   0
Percentage in Communication skills          0
Hours working per day                       0
Logical quotient rating                     0
hackathons                                  0
coding skills rating                        0
public speaking points                      0
can work long time before system?           0
self-learning capability?                   0
Extra-courses did                           0
certifications                              0
workshops                                   0
talenttests taken?                          0
olympiads                                   0
reading and writing skills                  0
memory capability score                     0
Interested subjects                         0
interested career area                      0
Job/Higher Studies?                         0
Type of company want to settle in?          0
Taken inputs from seniors or elders         0
interested in games                         0
Interested Type of Books                    0
Salary Range Expected                       0
In a Realtionship?                          0
Gentle or Tuff behaviour?                   0
Management or Technical                     0
Salary/work                                 0
hard/smart worker                           0
worked in teams ever?                       0
Introvert                                   0
Suggested Job Role                          0
dtype: int64

In [50]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Acedamic percentage in Operating Systems,20000.0,77.00230,10.085697,60.0,68.0,77.0,86.0,94.0
percentage in Algorithms,20000.0,76.94820,10.101733,60.0,68.0,77.0,86.0,94.0
Percentage in Programming Concepts,20000.0,77.01755,10.134815,60.0,68.0,77.0,86.0,94.0
Percentage in Software Engineering,20000.0,77.09450,10.087837,60.0,68.0,77.0,86.0,94.0
Percentage in Computer Networks,20000.0,76.95820,10.020088,60.0,68.0,77.0,85.0,94.0
Percentage in Electronics Subjects,20000.0,77.01555,10.168888,60.0,68.0,77.0,86.0,94.0
Percentage in Computer Architecture,20000.0,77.06985,10.069059,60.0,68.0,77.0,86.0,94.0
Percentage in Mathematics,20000.0,76.91310,10.138555,60.0,68.0,77.0,86.0,94.0
Percentage in Communication skills,20000.0,76.92145,10.103494,60.0,68.0,77.0,86.0,94.0
Hours working per day,20000.0,7.98595,2.593798,4.0,6.0,8.0,10.0,12.0
Logical quotient rating,20000.0,4.99505,2.578383,1.0,3.0,5.0,7.0,9.0
hackathons,20000.0,2.99265,2.005791,0.0,1.0,3.0,5.0,6.0
coding skills rating,20000.0,5.00475,2.576831,1.0,3.0,5.0,7.0,9.0
public speaking points,20000.0,5.01280,2.588875,1.0,3.0,5.0,7.0,9.0

In [51]:
df_copy = df.copy()

In [52]:
df_copy.head()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,69,63,78,87,94,94,87,84,61,9,...,Prayer books,salary,no,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,78,62,73,60,71,70,73,84,91,12,...,Childrens,salary,yes,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,71,86,91,87,61,81,72,72,94,11,...,Travel,Work,no,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,76,87,60,84,89,73,62,88,69,7,...,Romance,Work,yes,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,92,62,90,67,71,89,73,71,73,4,...,Cookbooks,salary,no,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst

In [53]:
def change_string_to_int(column):
    variables=pd.unique(df_copy[column])
    for item in range(variables.size):
        df_copy[column]=[item if each==variables[item] else each for each in df_copy[column]]
    return df_copy[column]

In [54]:
object_columns = df.select_dtypes(include=['object'])

for column in object_columns.columns:
    unique_elements = object_columns[column].unique()
    print(f"Unique elements in '{column}':")
    print(unique_elements)
    print("\n")

Unique elements in 'can work long time before system?':
['yes' 'no']


Unique elements in 'self-learning capability?':
['yes' 'no']


Unique elements in 'Extra-courses did':
['yes' 'no']


Unique elements in 'certifications':
['shell programming' 'machine learning' 'app development' 'python'
 'r programming' 'information security' 'hadoop' 'distro making'
 'full stack']


Unique elements in 'workshops':
['cloud computing' 'database security' 'web technologies' 'data science'
 'testing' 'hacking' 'game development' 'system designing']


Unique elements in 'talenttests taken?':
['no' 'yes']


Unique elements in 'olympiads':
['yes' 'no']


Unique elements in 'reading and writing skills':
['excellent' 'poor' 'medium']


Unique elements in 'memory capability score':
['excellent' 'medium' 'poor']


Unique elements in 'Interested subjects':
['cloud computing' 'networks' 'hacking' 'Computer Architecture'
 'programming' 'parallel computing' 'IOT' 'data engineering'
 'Software Engineering' 'Management']


Unique elements in 'interested career area ':
['system developer' 'Business process analyst' 'developer' 'testing'
 'security' 'cloud computing']


Unique elements in 'Job/Higher Studies?':
['higherstudies' 'job']


Unique elements in 'Type of company want to settle in?':
['Web Services' 'SAaS services' 'Sales and Marketing'
 'Testing and Maintainance Services' 'product development' 'BPA'
 'Service Based' 'Product based' 'Cloud Services' 'Finance']


Unique elements in 'Taken inputs from seniors or elders':
['no' 'yes']


Unique elements in 'interested in games':
['no' 'yes']


Unique elements in 'Interested Type of Books':
['Prayer books' 'Childrens' 'Travel' 'Romance' 'Cookbooks' 'Self help'
 'Drama' 'Math' 'Religion-Spirituality' 'Anthology' 'Trilogy'
 'Autobiographies' 'Mystery' 'Diaries' 'Journals' 'History' 'Art'
 'Dictionaries' 'Horror' 'Encyclopedias' 'Action and Adventure' 'Fantasy'
 'Comics' 'Science fiction' 'Series' 'Guide' 'Biographies' 'Health'
 'Satire' 'Science' 'Poetry']


Unique elements in 'Salary Range Expected':
['salary' 'Work']


Unique elements in 'In a Realtionship?':
['no' 'yes']


Unique elements in 'Gentle or Tuff behaviour?':
['stubborn' 'gentle']


Unique elements in 'Management or Technical':
['Management' 'Technical']


Unique elements in 'Salary/work':
['salary' 'work']


Unique elements in 'hard/smart worker':
['hard worker' 'smart worker']


Unique elements in 'worked in teams ever?':
['yes' 'no']


Unique elements in 'Introvert':
['no' 'yes']


Unique elements in 'Suggested Job Role':
['Database Developer' 'Portal Administrator'
 'Systems Security Administrator' 'Business Systems Analyst'
 'Software Systems Engineer' 'Business Intelligence Analyst'
 'CRM Technical Developer' 'Mobile Applications Developer' 'UX Designer'
 'Quality Assurance Associate' 'Web Developer'
 'Information Security Analyst' 'CRM Business Analyst' 'Technical Support'
 'Project Manager' 'Information Technology Manager' 'Programmer Analyst'
 'Design & UX' 'Solutions Architect' 'Systems Analyst'
 'Network Security Administrator' 'Data Architect' 'Software Developer'
 'E-Commerce Analyst' 'Technical Services/Help Desk/Tech Support'
 'Information Technology Auditor' 'Database Manager'
 'Applications Developer' 'Database Administrator' 'Network Engineer'
 'Software Engineer' 'Technical Engineer' 'Network Security Engineer'
 'Software Quality Assurance (QA) / Testing']

In [62]:
for column in object_columns.columns:
    label_encoder = LabelEncoder()

    numeric = label_encoder.fit_transform(df_copy[column].unique())
    df_copy[column] = label_encoder.transform(df_copy[column])
    # Create a new DataFrame with the original and encoded values
    encoded_df = pd.DataFrame({column: df[column].unique(), column+' Associated Number': numeric})
    print(encoded_df)

  can work long time before system?  \
0                               yes
1                                no

   can work long time before system? Associated Number
0                                                  1
1                                                  0
  self-learning capability?  self-learning capability? Associated Number
0                       yes                                            1
1                        no                                            0
  Extra-courses did  Extra-courses did Associated Number
0               yes                                    1
1                no                                    0
         certifications  certifications Associated Number
0     shell programming                                 8
1      machine learning                                 5
2       app development                                 0
3                python                                 6
4         r programming                                 7
5  information security                                 4
6                hadoop                                 3
7         distro making                                 1
8            full stack                                 2
           workshops  workshops Associated Number
0    cloud computing                            0
1  database security                            2
2   web technologies                            7
3       data science                            1
4            testing                            6
5            hacking                            4
6   game development                            3
7   system designing                            5
  talenttests taken?  talenttests taken? Associated Number
0                 no                                     0
1                yes                                     1
  olympiads  olympiads Associated Number
0       yes                            1
1        no                            0
  reading and writing skills  reading and writing skills Associated Number
0                  excellent                                             0
1                       poor                                             2
2                     medium                                             1
  memory capability score  memory capability score Associated Number
0               excellent                                          0
1                  medium                                          1
2                    poor                                          2
     Interested subjects  Interested subjects Associated Number
0        cloud computing                                      4
1               networks                                      7
2                hacking                                      6
3  Computer Architecture                                      0
4            programming                                      9
5     parallel computing                                      8
6                    IOT                                      1
7       data engineering                                      5
8   Software Engineering                                      3
9             Management                                      2
    interested career area   interested career area  Associated Number
0          system developer                                          4
1  Business process analyst                                          0
2                 developer                                          2
3                   testing                                          5
4                  security                                          3
5           cloud computing                                          1
  Job/Higher Studies?  Job/Higher Studies? Associated Number
0       higherstudies                                      0
1                 job                                      1
  Type of company want to settle in?  \
0                       Web Services
1                      SAaS services
2                Sales and Marketing
3  Testing and Maintainance Services
4                product development
5                                BPA
6                      Service Based
7                      Product based
8                     Cloud Services
9                            Finance

   Type of company want to settle in? Associated Number
0                                                  8
1                                                  4
2                                                  5
3                                                  7
4                                                  9
5                                                  0
6                                                  6
7                                                  3
8                                                  1
9                                                  2
  Taken inputs from seniors or elders  \
0                                  no
1                                 yes

   Taken inputs from seniors or elders Associated Number
0                                                  0
1                                                  1
  interested in games  interested in games Associated Number
0                  no                                      0
1                 yes                                      1
   Interested Type of Books  Interested Type of Books Associated Number
0              Prayer books                                          21
1                 Childrens                                           5
2                    Travel                                          29
3                   Romance                                          23
4                 Cookbooks                                           7
5                 Self help                                          27
6                     Drama                                          10
7                      Math                                          18
8     Religion-Spirituality                                          22
9                 Anthology                                           1
10                  Trilogy                                          30
11          Autobiographies                                           3
12                  Mystery                                          19
13                  Diaries                                           8
14                 Journals                                          17
15                  History                                          15
16                      Art                                           2
17             Dictionaries                                           9
18                   Horror                                          16
19            Encyclopedias                                          11
20     Action and Adventure                                           0
21                  Fantasy                                          12
22                   Comics                                           6
23          Science fiction                                          26
24                   Series                                          28
25                    Guide                                          13
26              Biographies                                           4
27                   Health                                          14
28                   Satire                                          24
29                  Science                                          25
30                   Poetry                                          20
  Salary Range Expected  Salary Range Expected Associated Number
0                salary                                        1
1                  Work                                        0
  In a Realtionship?  In a Realtionship? Associated Number
0                 no                                     0
1                yes                                     1
  Gentle or Tuff behaviour?  Gentle or Tuff behaviour? Associated Number
0                  stubborn                                            1
1                    gentle                                            0
  Management or Technical  Management or Technical Associated Number
0              Management                                          0
1               Technical                                          1
  Salary/work  Salary/work Associated Number
0      salary                              0
1        work                              1
  hard/smart worker  hard/smart worker Associated Number
0       hard worker                                    0
1      smart worker                                    1
  worked in teams ever?  worked in teams ever? Associated Number
0                   yes                                        1
1                    no                                        0
  Introvert  Introvert Associated Number
0        no                            0
1       yes                            1
                           Suggested Job Role  \
0                          Database Developer
1                        Portal Administrator
2              Systems Security Administrator
3                    Business Systems Analyst
4                   Software Systems Engineer
5               Business Intelligence Analyst
6                     CRM Technical Developer
7               Mobile Applications Developer
8                                 UX Designer
9                 Quality Assurance Associate
10                              Web Developer
11               Information Security Analyst
12                       CRM Business Analyst
13                          Technical Support
14                            Project Manager
15             Information Technology Manager
16                         Programmer Analyst
17                                Design & UX
18                        Solutions Architect
19                            Systems Analyst
20             Network Security Administrator
21                             Data Architect
22                         Software Developer
23                         E-Commerce Analyst
24  Technical Services/Help Desk/Tech Support
25             Information Technology Auditor
26                           Database Manager
27                     Applications Developer
28                     Database Administrator
29                           Network Engineer
30                          Software Engineer
31                         Technical Engineer
32                  Network Security Engineer
33  Software Quality Assurance (QA) / Testing

    Suggested Job Role Associated Number
0                                      7
1                                     18
2                                     28
3                                      2
4                                     25
5                                      1
6                                      4
7                                     14
8                                     32
9                                     21
10                                    33
11                                    11
12                                     3
13                                    31
14                                    20
15                                    13
16                                    19
17                                     9
18                                    26
19                                    27
20                                    16
21                                     5
22                                    22
23                                    10
24                                    30
25                                    12
26                                     8
27                                     0
28                                     6
29                                    15
30                                    23
31                                    29
32                                    17
33                                    24

In [63]:
df_copy.head()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,69,63,78,87,94,94,87,84,61,9,...,21,1,0,1,0,0,0,1,0,7
1,78,62,73,60,71,70,73,84,91,12,...,5,1,1,0,1,0,0,0,1,18
2,71,86,91,87,61,81,72,72,94,11,...,29,0,0,1,0,1,0,0,1,18
3,76,87,60,84,89,73,62,88,69,7,...,23,0,1,0,0,1,1,1,1,28
4,92,62,90,67,71,89,73,71,73,4,...,7,1,0,1,0,1,0,1,1,2

In [57]:
# object_columns = df.select_dtypes(include=['object'])

# for column in object_columns.columns:
#     print(f"Description of '{column}':")
#     print(object_columns[column].describe())
#     print("\n")

In [58]:
# # List of columns to be label encoded
# columns_to_encode = [
#     'can work long time before system?', 'self-learning capability?', 'Extra-courses did',
#     'talenttests taken?', 'olympiads', 'In a Realtionship?', 'Gentle or Tuff behaviour?',
#     'Management or Technical', 'Salary/work', 'hard/smart worker', 'worked in teams ever?', 'Introvert',
#     'Taken inputs from seniors or elders','interested in games','Job/Higher Studies?','Salary Range Expected'
# ]

# # Initialize the LabelEncoder
# label_encoder = LabelEncoder()

# # Apply label encoding to the specified columns
# for column in columns_to_encode:
#     df_copy[column] = label_encoder.fit_transform(df_copy[column])
#     # print(df_copy[column])
# # Display the first few rows to verify the changes
# df_copy.head()

## Splitting the Dataset into Features and Target Variable

To prepare the dataset for modeling, we need to split it into features (`X`) and the target variable (`y`). The target variable in this dataset is `Suggested Job Role`, and the remaining columns will be used as features.

The following code performs this split:

```python
y = df['Suggested Job Role']
X = df.drop(columns=['Suggested Job Role'])
```

This will create two new variables, `X` and `y`, which can be used for training machine learning models.

In [59]:
# # Define the target variable
# y = df['Suggested Job Role']

# # Define the feature variables
# X = df.drop(columns=['Suggested Job Role'])

# # Display the shapes of X and y to verify
# print(f"Shape of X: {X.shape}")
# print(f"Shape of y: {y.shape}")

In [60]:
# df_copy.info()